
import java.awt.Font;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class InventorySummary extends javax.swing.JFrame {

    /**
     * Creates new form InventorySummary
     */
    public InventorySummary() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        DisplayData();
    }
    
    private void tblHeader()
    {
        JTableHeader tHeader = tblDisplay.getTableHeader();
        tHeader.setFont(new Font("Tahome", Font.BOLD, 20));
        tHeader.setForeground(java.awt.Color.WHITE);
        tHeader.setBackground(java.awt.Color.DARK_GRAY);
    }
    
    private ArrayList<Item> fetchInventoryData()
    {
        ArrayList<Item> data = new ArrayList<>();
        
        String query = "SELECT * FROM INVENTORY";
        Statement st;
        try {
            DatabaseConnect db = new DatabaseConnect();
            st = db.conn.createStatement();
            ResultSet rs =  st.executeQuery(query);
            Item item;
            while(rs.next())
            {
                item = new Item(rs.getString("PID"), rs.getInt("QUANTITY"), rs.getInt("BREAKAGE"), rs.getInt("NET"));
                data.add(item);
            }
            st.close();
            
        } catch (SQLException ex) {
            System.out.println("Error in Fetching data");
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(InventorySummary.class.getName()).log(Level.SEVERE, null, ex);
        }
        return data;
        
    }
    
    private void DisplayData()
    {
        ArrayList<Item> data = fetchInventoryData();
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        Object[] row = new Object[4];
        
        int quant = 0, damage = 0, net = 0;
        for(int i=0; i<data.size(); i++)
        {
            row[0] = data.get(i).getPid();
            row[1] = data.get(i).getQuant();
            row[2] = data.get(i).getBreakage();
            row[3] = data.get(i).getNet();
            quant += data.get(i).getQuant();
            damage += data.get(i).getBreakage();
            net += data.get(i).getNet();
            
            model.addRow(row);
        }
//        row[0] = "";
//        row[1] = "";
//        row[2] = "";
//        row[3] = "";
//        model.addRow(row);
        
        row[0] = "Total";
        row[1] = quant;
        row[2] = damage;
        row[3] = net;
        model.addRow(row);
        tblHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        btnExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("INVENTORY SUMMARY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        tblDisplay.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pid", "Quantity", "Breakage", "Net"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplay.setRowHeight(20);
        jScrollPane1.setViewportView(tblDisplay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 1300, 510));

        btnExcel.setBackground(new java.awt.Color(0, 51, 51));
        btnExcel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnExcel.setForeground(new java.awt.Color(255, 255, 255));
        btnExcel.setText("GENERATE EXCEL SHEET");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 93, 310, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        String currentDir = System.getProperty("user.home") + "\\Desktop\\SalesSummary";
        Exporter exp = new Exporter();
        String tstamp = GenerateStamp();
        String path = currentDir + tstamp + ".csv";
        System.out.println("Path is " + path);
        exp.exportTable(tblDisplay, new File(path));
        JOptionPane.showMessageDialog(null, "Excel File created on Desktop.");
    }//GEN-LAST:event_btnExcelActionPerformed
    
    private String GenerateStamp()
    {
        Date dt = new Date();
        String stamp = new SimpleDateFormat("yyyyMMddHHmmss").format(new Timestamp(dt.getTime()));
        return stamp;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventorySummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventorySummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventorySummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventorySummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InventorySummary().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisplay;
    // End of variables declaration//GEN-END:variables
}
