
import java.awt.Font;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class ProductwiseSummary extends javax.swing.JFrame {

    /**
     * Creates new form ProductwiseSummary
     */
    public ProductwiseSummary() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        loadTable();
    }
    
    private void tblHeader()
    {
        JTableHeader tHeader = tblDisplay.getTableHeader();
        tHeader.setFont(new Font("Tahome", Font.BOLD, 20));
        tHeader.setForeground(java.awt.Color.WHITE);
        tHeader.setBackground(java.awt.Color.DARK_GRAY);
    }
    
    private void loadTable()
    {
        ArrayList<String> data = findProducts();
        int total = 0;
        for(int i=0; i<data.size(); i++)
        {
            int purchase = findTotal("PURCHASE", data.get(i));
            int sales = findTotal("SALES", data.get(i));
            insertInTable(data.get(i),purchase,sales);
            total += (sales - purchase);
        }
        generateTotal(total);
        tblHeader();
    }
    
    
    private ArrayList<String> findProducts()
    {
        String sql = "SELECT PID FROM INVENTORY";
        ArrayList<String> data = new ArrayList<>();
        try{
            DatabaseConnect db = new DatabaseConnect();
            PreparedStatement pst = db.conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next())
            {
                data.add(rs.getString(1));
            }
            pst.close();
               
        } catch (SQLException ex) {
                Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(ProductwiseSummary.class.getName()).log(Level.SEVERE, null, ex);
        }
        return data;
    }
    
    private int findTotal(String dep, String pid)
    {
        int total = 0;
        try
        {
            String sql = "SELECT SUM(TOTAL) FROM " + dep + " WHERE PID=?";
            DatabaseConnect db = new DatabaseConnect();
            PreparedStatement pst = db.conn.prepareStatement(sql);
            pst.setString(1, pid);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                total = rs.getInt(1);
            }
            pst.close();
               
        } catch (SQLException ex) {
                Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(ProductwiseSummary.class.getName()).log(Level.SEVERE, null, ex);
        }
        return total;
    }

    private void insertInTable(String pid, int purchase, int sales)
    {
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        Object[] row = new Object[4];
        
        int net = sales - purchase;
        row[0] = pid;
        row[1] = purchase;
        row[2] = sales;
        row[3] = net;
        model.addRow(row);
    }
    
    private void generateTotal(int total)
    {
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        Object[] row = new Object[4];
        
        row[0] = "Total";
        row[1] = "";
        row[2] = "";
        row[3] = total;
        model.addRow(row);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDisplay.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pid", "Total Purchase", "Total Sale", "Net"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplay.setRowHeight(20);
        jScrollPane1.setViewportView(tblDisplay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 1320, 520));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("PRODUCT REVENUE SUMMARY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GENERATE EXCEL SHEET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, 300, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String currentDir = System.getProperty("user.home") + "\\Desktop\\ProductwiseSummary";
        Exporter exp = new Exporter();
        String tstamp = GenerateStamp();
        String path = currentDir + tstamp + ".csv";
        System.out.println("Path is " + path);
        exp.exportTable(tblDisplay, new File(path));
        JOptionPane.showMessageDialog(null, "Excel File created on Desktop.");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private String GenerateStamp()
    {
        Date dt = new Date();
        String stamp = new SimpleDateFormat("yyyyMMddHHmmss").format(new Timestamp(dt.getTime()));
        return stamp;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductwiseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductwiseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductwiseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductwiseSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ProductwiseSummary().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisplay;
    // End of variables declaration//GEN-END:variables
}
