
import java.awt.Font;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Purchase extends javax.swing.JFrame {

    /**
     * Creates new form Purchase
     * @throws java.lang.IllegalAccessException
     */
    public Purchase() throws IllegalAccessException {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        DisplayData();
    }
    
    private void tblHeader()
    {
        JTableHeader tHeader = tblDisplay.getTableHeader();
        tHeader.setFont(new Font("Tahome", Font.BOLD, 20));
        tHeader.setForeground(java.awt.Color.WHITE);
        tHeader.setBackground(java.awt.Color.BLUE);
    }
    
    
    // Purchase table data fetching
    private ArrayList<Record> fetchData() throws IllegalAccessException
    {
        ArrayList<Record> data = new ArrayList<>();
        
        String query = "SELECT * FROM PURCHASE ORDER BY DATE DESC";
        Statement st;
        try {
            DatabaseConnect db = new DatabaseConnect();
    
            st = db.conn.createStatement();
            ResultSet rs =  st.executeQuery(query);
            Record rec;
            while(rs.next())
            {
                rec = new Record(rs.getString("PID"), rs.getTimestamp("DATE"), rs.getInt("QUANTITY"), rs.getInt("RATE"), rs.getInt("TOTAL"));
                data.add(rec);
            }
            st.close();
            
        } catch (SQLException ex) {
            System.out.println("Error in Fetching data");
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | InstantiationException ex) {
            Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
        }
        return data;
        
    }
    
    private void DisplayData() throws IllegalAccessException
    {
        ArrayList<Record> data = fetchData();
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        Object[] row = new Object[5];
        
        for(int i=0; i<data.size(); i++)
        {
            row[0] = data.get(i).getDate();
            row[1] = data.get(i).getPid();
            row[2] = data.get(i).getQuant();
            row[3] = data.get(i).getRate();
            row[4] = data.get(i).getTotal();
            model.addRow(row);
        }
        tblHeader();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPurchase = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurchase.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblPurchase.setText("Purchase Records");
        getContentPane().add(lblPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        tblDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Pid", "Quantity", "Rate", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplay.setInheritsPopupMenu(true);
        tblDisplay.setRowHeight(20);
        tblDisplay.setRowMargin(2);
        jScrollPane2.setViewportView(tblDisplay);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 1260, 460));

        btnDelete.setBackground(new java.awt.Color(0, 102, 102));
        btnDelete.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 133, 190, 50));

        btnExcel.setBackground(new java.awt.Color(0, 102, 102));
        btnExcel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnExcel.setForeground(new java.awt.Color(255, 255, 255));
        btnExcel.setText("Create Excel Sheet");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 133, 280, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        String currentDir = System.getProperty("user.home") + "\\Desktop\\Purchase";
        Exporter exp = new Exporter();
        String tstamp = GenerateStamp();
        String path = currentDir + tstamp + ".csv";
        System.out.println("Path is " + path);
        exp.exportTable(tblDisplay, new File(path));
        JOptionPane.showMessageDialog(null, "Excel File created on Desktop.");
        
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        
        if(tblDisplay.getSelectedRowCount() == 1)
        {
            int row = tblDisplay.getSelectedRow();
            String sql = "DELETE FROM PURCHASE WHERE PID=?";
            try {
                
                DatabaseConnect db = new DatabaseConnect();
                PreparedStatement pst = db.conn.prepareStatement(sql);
                pst.setString(1, (String) model.getValueAt(row, 1));
                pst.execute();
                model.removeRow(row);
                JOptionPane.showMessageDialog(null, "Deleted Successfully");
                pst.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Something went wrong!");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else
        {
            if(tblDisplay.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(null, "No Record is Present!");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please select a single row!");
               
            }
        }    
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    private String GenerateStamp()
    {
        Date dt = new Date();
        String stamp = new SimpleDateFormat("yyyyMMddHHmmss").format(new Timestamp(dt.getTime()));
        return stamp;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Purchase().setVisible(true);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    public JTable getTblDisplay() {
        return tblDisplay;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExcel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPurchase;
    private javax.swing.JTable tblDisplay;
    // End of variables declaration//GEN-END:variables
}
