
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class PurchaseItem extends javax.swing.JFrame {

    /**
     * Creates new form UpateItem
     */
    public PurchaseItem() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPid = new javax.swing.JLabel();
        txtPid = new javax.swing.JTextField();
        lblQuant = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBreak = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("PURCHASE ITEM");

        lblPid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPid.setText("Product Id");

        txtPid.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        lblQuant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuant.setText("Quantity");

        txtQuant.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantActionPerformed(evt);
            }
        });
        txtQuant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Breakage");

        txtBreak.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtBreak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBreakKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Rate");

        txtRate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateActionPerformed(evt);
            }
        });
        txtRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRateKeyPressed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 51, 51));
        btnUpdate.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Purchase");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 468, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuant)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(118, 118, 118))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPid)
                                    .addGap(108, 108, 108)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRate, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(txtQuant, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(txtBreak, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(txtPid, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))))
                .addGap(462, 462, 462))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPid)
                    .addComponent(txtPid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuant)
                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBreak, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateActionPerformed

    private void txtQuantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtQuant.setEditable(false);
        } else {
            txtQuant.setEditable(true);
        }
    }//GEN-LAST:event_txtQuantKeyPressed

    private void txtBreakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBreakKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtBreak.setEditable(false);
        } else {
            txtBreak.setEditable(true);
        }
    }//GEN-LAST:event_txtBreakKeyPressed

    private void txtRateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRateKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtRate.setEditable(false);
        } else {
            txtRate.setEditable(true);
        }
    }//GEN-LAST:event_txtRateKeyPressed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (validateProductInfo()) {
            addToPurchase();
            if (checkInventory()) {
                updateInventory();
                JOptionPane.showMessageDialog(null, "The product is updated in Inventory!");
            } else {
                addToInventory();
                JOptionPane.showMessageDialog(null, "New product added to Inventory!");
            }
            resetValues();
            new Inventory().setVisible(true);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantActionPerformed

    private void txtQuantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantKeyTyped

    private boolean validateProductInfo() {
        if (txtPid.getText().trim().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Please enter a Product id");
            return false;
        }
        if (txtQuant.getText().trim().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Please enter some Quantity");
            return false;
        }
        if (txtBreak.getText().trim().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Please enter breakage Quantity");
            return false;
        }
        if (txtRate.getText().trim().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Please enter rate of purchase");
            return false;
        }

        return true;
    }

    private void addToPurchase() 
    {
        String sql = "INSERT INTO PURCHASE (PID, DATE, QUANTITY, RATE, TOTAL) VALUES (?,?,?,?,?)";
        try {
            DatabaseConnect db = new DatabaseConnect();

            String pattern = "yyyy-MM-dd HH:mm:ss";
            Date dt = new Date();
            String stamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Timestamp(dt.getTime()));
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(pattern);
            LocalDateTime localDateTime = LocalDateTime.from(formatter.parse(stamp));
            Timestamp tstamp = Timestamp.valueOf(localDateTime);

            int total = Integer.parseInt(txtQuant.getText().trim()) * Integer.parseInt(txtRate.getText().trim());
            PreparedStatement pst = db.conn.prepareStatement(sql);
            pst.setString(1, txtPid.getText().trim());
            pst.setTimestamp(2, tstamp);
            pst.setInt(3, Integer.parseInt(txtQuant.getText().trim()));
            pst.setInt(4, Integer.parseInt(txtRate.getText().trim()));
            pst.setInt(5, total);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Item added in purchased list!");
            pst.close();
        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(PurchaseItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean checkInventory() 
    {
        try 
        {
            DatabaseConnect db = new DatabaseConnect();
            String sql = "SELECT * FROM INVENTORY WHERE PID=?";
            PreparedStatement pst = db.conn.prepareStatement(sql);
            pst.setString(1, txtPid.getText().trim());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) 
            {
                return true;
            }
            pst.close();
        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(PurchaseItem.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private void updateInventory() 
    {
        int quant = 0, damage = 0;
        try {
            String sql = "SELECT * FROM INVENTORY WHERE PID=?";
            DatabaseConnect db = new DatabaseConnect();
            PreparedStatement pst = db.conn.prepareStatement(sql);
            pst.setString(1, txtPid.getText().trim());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                quant = rs.getInt("QUANTITY");
                damage = rs.getInt("BREAKAGE");
            }
            pst.close();
        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(PurchaseItem.class.getName()).log(Level.SEVERE, null, ex);
        }

        String sql = "UPDATE INVENTORY SET PID=?, QUANTITY=?, BREAKAGE=?, NET=? WHERE PID=?";
        try {
            quant += Integer.parseInt(txtQuant.getText().trim());
            damage += Integer.parseInt(txtBreak.getText().trim());

            int net = quant - damage;

            DatabaseConnect db = new DatabaseConnect();
            PreparedStatement pst = db.conn.prepareStatement(sql);
            pst.setString(1, txtPid.getText().trim());
            pst.setInt(2, quant);
            pst.setInt(3, damage);
            pst.setInt(4, net);
            pst.setString(5, txtPid.getText().trim());
            pst.executeUpdate();
            pst.close();

        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(PurchaseItem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void addToInventory() 
    {
        String sql = "INSERT INTO INVENTORY (PID,QUANTITY,BREAKAGE,NET) VALUES (?,?,?,?)";
        try {
            int net = Integer.parseInt(txtQuant.getText().trim()) - Integer.parseInt(txtBreak.getText().trim());
            DatabaseConnect db = new DatabaseConnect();
            PreparedStatement pst = db.conn.prepareStatement(sql);
            pst.setString(1, txtPid.getText().trim());
            pst.setInt(2, Integer.parseInt(txtQuant.getText().trim()));
            pst.setInt(3, Integer.parseInt(txtBreak.getText().trim()));
            pst.setInt(4, net);

            pst.execute();
            pst.close();
        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(PurchaseItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resetValues() {
        txtPid.setText("");
        txtBreak.setText("");
        txtQuant.setText("");
        txtRate.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PurchaseItem().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JTextField txtBreak;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtRate;
    // End of variables declaration//GEN-END:variables
}
